# Basic Information 
title: Thai-Hoc Nguyen
position: AI Researcher
affiliation: Institute of Applied Science and Technology (IAST), Thai Nguyen
email: thaihoc.it02@gmail.com


keywords: minimal light
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: https://minimal-light-theme.yliu.me/


google_scholar: https://scholar.google.com/citations?user=SvS3rssAAAAJ&hl=vi
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/nthaihoc
affiliation_link: https://iast.ictu.edu.vn

avatar: ./assets/img/avatar.jpeg
favicon: 
favicon_dark:


enable_footnote: true
auto_dark_mode: true


font: "Serif"
google_analytics: UA-111540567-4
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/